make
    ## needed to set indent
        git
            python ..\..\python\vyAlias\tests\main.py input/git.vyalias -o output -f g.vyalias.cmd
            snippet: <= Generate git alias files from both, vyalias & python, config files
        link
            del g.cmd
            mklink g.cmd output\g.vyalias.cmd
        make
            python ../../python/vyAlias/tests/main.py input/makefile.vyalias
            snippet: <= Generates this make batch file from its config file
